# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokener < Formula
  desc "Command-line client and agent launcher for Tokener.ai"
  homepage "https://tokener.dev/"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langgenius/tokener-cli/releases/download/v0.1.5/tokener_0.1.5_darwin_amd64.tar.gz"
      sha256 "59e2c6d5abf4d92f4929de9888716bd17a2db65e6018fbc01b58f9da005fd814"

      define_method(:install) do
        bin.install "tokener"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langgenius/tokener-cli/releases/download/v0.1.5/tokener_0.1.5_darwin_arm64.tar.gz"
      sha256 "0bede4a624b43026bcfaf360d928562524df47fb6fe2780bd642dbd8e0b499ce"

      define_method(:install) do
        bin.install "tokener"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/tokener-cli/releases/download/v0.1.5/tokener_0.1.5_linux_amd64.tar.gz"
      sha256 "f76572d98da05fd84c8451eee0f4b4e46c11e977e013ca07a5807250f4081c76"
      define_method(:install) do
        bin.install "tokener"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokener --version")
    system "#{bin}/tokener", "commands", "--json"
    system "#{bin}/tokener", "agent", "--help"
  end
end
