# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokener < Formula
  desc "Command-line client and agent launcher for Tokener.ai"
  homepage "https://tokener.dev/"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langgenius/tokener-cli/releases/download/v0.1.2/tokener_0.1.2_darwin_amd64.tar.gz"
      sha256 "2efef3c5e54493a9ad1d63ef59eabdc05678aa7472df16b6c0813da9884a29e7"

      define_method(:install) do
        bin.install "tokener"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langgenius/tokener-cli/releases/download/v0.1.2/tokener_0.1.2_darwin_arm64.tar.gz"
      sha256 "e7e91d63aee5f44ca35b227ada0cd145b7934190d8db7844f9370bb2d966468e"

      define_method(:install) do
        bin.install "tokener"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/tokener-cli/releases/download/v0.1.2/tokener_0.1.2_linux_amd64.tar.gz"
      sha256 "de463d672f10ada4e6d53d583156dc9a8df59d2d8903b1a3fac011570b9ec4c3"
      define_method(:install) do
        bin.install "tokener"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokener --version")
    system "#{bin}/tokener", "commands", "--json"
    system "#{bin}/tokener", "agent", "--help"
  end
end
