# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokener < Formula
  desc "Command-line client and agent launcher for Tokener.ai"
  homepage "https://tokener.dev/"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/langgenius/tokener-cli/releases/download/v0.1.1/tokener_0.1.1_darwin_amd64.tar.gz"
      sha256 "8564aefbd11d78ae0fd63c99073665e7d7d2b0109caeda6225a8aad8de77ccb1"

      define_method(:install) do
        bin.install "tokener"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/langgenius/tokener-cli/releases/download/v0.1.1/tokener_0.1.1_darwin_arm64.tar.gz"
      sha256 "988bb4510c9e2cc48f53a89fed919967832f51d10f3aa295791472d2fc27fc29"

      define_method(:install) do
        bin.install "tokener"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/langgenius/tokener-cli/releases/download/v0.1.1/tokener_0.1.1_linux_amd64.tar.gz"
      sha256 "f36136ce5c2df32dedac63d7e33760db4d6fecf3e09d6d17cb36ed833b6de896"
      define_method(:install) do
        bin.install "tokener"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tokener --version")
    system "#{bin}/tokener", "commands", "--json"
    system "#{bin}/tokener", "agent", "--help"
  end
end
